export enum Services {
  AUTH = 'AUTH',
  CREATE_TASK = 'CREATE_TASK',
  DELETE_TASK = 'DELETE_TASK',
  LOAD_TASKS = 'LOAD_TASKS',
  UPDATE_TASK = 'UPDATE_TASK',
  LOAD_PERFORMANCE = 'LOAD_PERFORMANCE',
  UPDATE_PERFORMANCE = 'UPDATE_PERFORMANCE',
  SEND_EMAIL = 'SEND_EMAIL',
  AUTH_MIDDLEWARE = 'AUTH_MIDDLEWARE',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
}
